services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco
    volumes:
      - "G:/Meu Drive/postgres-data:/var/lib/postgresql/data"
