services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: SuperUser
      POSTGRES_PASSWORD: tms@82815523
      POSTGRES_DB: supermarketScanner
    volumes:
      - "G:/My Drive/Database/SuperMarket:/var/lib/postgresql/data"
